.circleci/config.yml
.gitignore
pom.xml
src/main/frontend/.gitignore
src/test/kotlin/io/fabric8/launcher/quarkus/LauncherQuarkusTest.kt

test: add basic download tests

---

src/main/frontend/src/app/pickers/__tests__/__snapshots__/extensions-picker.spec.tsx.snap
src/main/frontend/src/app/pickers/extensions-picker.scss
src/main/frontend/src/app/pickers/extensions-picker.tsx

fix: enhance UX

---

src/main/frontend/src/app/pickers/__tests__/__snapshots__/extensions-picker.spec.tsx.snap
src/main/frontend/src/app/pickers/extensions-picker.tsx

fix: use empty check in list and change icons

---

src/main/frontend/src/app/extensions-loader.tsx
src/main/frontend/src/app/pickers/__tests__/__snapshots__/extensions-picker.spec.tsx.snap
src/main/frontend/src/app/pickers/__tests__/extensions-picker.spec.tsx
src/main/frontend/src/app/pickers/extensions-picker.tsx

fix: change search algo

---

src/main/frontend/src/app/header.scss
src/main/frontend/src/app/header.tsx
src/main/frontend/src/app/pickers/extensions-picker.scss
src/main/frontend/src/app/quarkus-app.scss
src/main/frontend/src/app/quarkus-form.scss
src/main/frontend/src/app/quarkus-form.tsx

I've implemented a very basic responsive design so that at least it doesn't look buggy on smaller display and mobiles:
I've also implemented a display for medium width display where we don't show extended project infos:
Closes #45

feat: introduce basic responsive design

---

src/main/frontend/public/index.html
src/main/frontend/src/index.tsx
src/main/frontend/src/launcher-quarkus/__tests__/launcher-quarkus.spec.tsx
src/main/frontend/src/launcher-quarkus/config-loader.tsx
src/main/frontend/src/launcher-quarkus/launcher-quarkus.tsx
src/main/frontend/src/launcher-quarkus/pickers/extensions-picker.tsx
src/main/kotlin/io/fabric8/launcher/quarkus/LauncherQuarkus.kt
src/main/kotlin/io/fabric8/launcher/quarkus/model/Config.kt
src/test/kotlin/io/fabric8/launcher/quarkus/LauncherQuarkusTest.kt

feat: introduce google analytics and configuration

---

src/main/frontend/package.json
src/main/frontend/src/launcher-quarkus/pickers/__tests__/__snapshots__/extensions-picker.spec.tsx.snap
src/main/frontend/src/launcher-quarkus/pickers/__tests__/extensions-picker.spec.tsx
src/main/frontend/src/launcher-quarkus/pickers/extensions-picker-helpers.ts
src/main/frontend/src/launcher-quarkus/pickers/extensions-picker.scss
src/main/frontend/src/launcher-quarkus/pickers/extensions-picker.tsx

Closes #80
Closes #75
Closes #35

Multiple features

---

src/main/frontend/src/launcher-quarkus/pickers/__tests__/__snapshots__/extensions-picker.spec.tsx.snap
src/main/frontend/src/launcher-quarkus/pickers/extensions-picker.tsx

Small typo fix - double dots

---

src/main/frontend/src/launcher-quarkus/form.scss
src/main/frontend/src/launcher-quarkus/launcher-quarkus.scss
src/main/frontend/src/launcher-quarkus/pickers/__tests__/__snapshots__/extensions-picker.spec.tsx.snap
src/main/frontend/src/launcher-quarkus/pickers/extensions-picker.scss
src/main/frontend/src/launcher-quarkus/pickers/extensions-picker.tsx
src/test/kotlin/io/launcher/quarkus/QuarkusProjectCreatorTest.kt

 fix: add mobile info about generate

---

src/main/kotlin/io/launcher/quarkus/LauncherQuarkusResource.kt
src/main/kotlin/io/launcher/quarkus/QuarkusProjectCreator.kt
src/main/kotlin/io/launcher/quarkus/writer/CommonsZipProjectWriter.java
src/test/kotlin/io/launcher/quarkus/LauncherQuarkusResourceTest.kt
src/test/kotlin/io/launcher/quarkus/ProjectTestHelpers.kt
src/test/kotlin/io/launcher/quarkus/QuarkusProjectCreatorMock.kt
src/test/kotlin/io/launcher/quarkus/QuarkusProjectCreatorTest.kt

- fix bug
- added tests
Closes #102

fix: pom.xml was never replaced after adding extensions

---

src/main/kotlin/io/launcher/quarkus/QuarkusProjectCreator.kt
src/test/kotlin/io/launcher/quarkus/LauncherQuarkusResourceTest.kt
src/test/kotlin/io/launcher/quarkus/QuarkusProjectCreatorMock.kt

use `@Singleton` instead of `@ApplicationScoped` because `@ApplicationScoped` is not working as expected.

test: add mocked tests for the download endpoint

---

src/main/frontend/src/code-quarkus/pickers/extensions-picker.scss
src/main/frontend/src/code-quarkus/pickers/extensions-picker.tsx

Fix event bug on extension picker

---

src/main/frontend/package.json
src/main/frontend/src/code-quarkus/__tests__/launcher-quarkus.spec.tsx
src/main/frontend/src/code-quarkus/code-quarkus.tsx
src/main/frontend/src/code-quarkus/config-loader.tsx
src/main/frontend/src/code-quarkus/copy-to-clipboard.tsx
src/main/frontend/src/code-quarkus/extensions-loader.tsx
src/main/frontend/src/code-quarkus/form.scss
src/main/frontend/src/code-quarkus/form.tsx
src/main/frontend/src/code-quarkus/next-steps.tsx
src/main/frontend/src/code-quarkus/pickers/__tests__/__snapshots__/info-picker.spec.tsx.snap
src/main/frontend/src/code-quarkus/pickers/__tests__/info-picker.spec.tsx
src/main/frontend/src/code-quarkus/pickers/extensions-picker.tsx
src/main/frontend/src/code-quarkus/pickers/info-picker.tsx
src/main/frontend/src/core/analytics/analytics-context.ts
src/main/frontend/src/core/analytics/analytics.ts
src/main/frontend/src/core/analytics/google-analytics.ts
src/main/frontend/src/core/analytics/index.ts
src/main/frontend/src/core/data-loader/data-loader.tsx
src/main/frontend/src/core/extended-text-input.tsx
src/main/frontend/src/core/index.ts
src/main/frontend/src/core/stuff.module.scss
src/main/frontend/src/core/stuff.tsx
src/main/frontend/src/core/toggle-panel/__tests__/__snapshots__/toggle-panel.spec.tsx.snap
src/main/frontend/src/core/toggle-panel/__tests__/toggle-panel.spec.tsx
src/main/frontend/src/core/toggle-panel/toggle-panel.scss
src/main/frontend/src/core/toggle-panel/toggle-panel.tsx
src/main/frontend/src/core/types.ts
src/main/frontend/tsconfig.json
src/main/frontend/yarn.lock

Use groupId for package name when untouched. Closes #124

Migrate @launcher/component in directory core

---

src/main/frontend/src/code-quarkus/form.tsx

Ensure validation when using alt+enter

---

src/main/frontend/src/code-quarkus/pickers/extensions-picker.tsx

fix: remove input select textarea filter

---

src/main/frontend/src/code-quarkus/backend-api.ts
src/main/frontend/src/code-quarkus/pickers/extensions-picker.tsx

fix: introduced included property for included extendsions

---

src/main/frontend/package.json
src/main/frontend/src/code-quarkus/copy-to-clipboard.tsx
src/main/frontend/src/code-quarkus/next-steps.tsx
src/main/frontend/src/code-quarkus/pickers/__tests__/__snapshots__/extensions-picker.spec.tsx.snap
src/main/frontend/src/code-quarkus/pickers/extensions-picker.scss
src/main/frontend/src/code-quarkus/pickers/extensions-picker.tsx
src/main/frontend/yarn.lock

- Make copy to clipboard nicer when copying
- Use display flex instead of grid for the extension table (because of some selection issues)
- Make keyboard selection more obvious
- Avoid up/down in search
- Make hotkey filter only allow the search input
- Keyboard select on mouse select

Fix multiple UI issues

---

src/main/frontend/src/code-quarkus/pickers/extensions-picker.scss
src/main/frontend/src/code-quarkus/pickers/extensions-picker.tsx

Make default extensions nicer

---

src/test/kotlin/io/quarkus/code/services/QuarkusProjectCreatorTest.kt

Use the same platform used for the main application in the test

---

src/main/frontend/src/code-quarkus/pickers/info-picker.tsx

Fix: Cannot delete contents of package name

---

src/main/frontend/src/code-quarkus/config.scss
src/main/frontend/src/code-quarkus/pickers/extensions-picker.scss
src/main/frontend/src/code-quarkus/pickers/extensions-picker.tsx

Introduce new experimental flag support

---

src/main/frontend/package.json
src/main/frontend/src/code-quarkus/code-quarkus.scss
src/main/frontend/src/code-quarkus/config.scss
src/main/frontend/src/code-quarkus/copy-to-clipboard.tsx
src/main/frontend/src/code-quarkus/extensions-loader.tsx
src/main/frontend/src/code-quarkus/pickers/__tests__/__snapshots__/extensions-picker.spec.tsx.snap
src/main/frontend/src/code-quarkus/pickers/extensions-picker.scss
src/main/frontend/src/code-quarkus/pickers/extensions-picker.tsx
src/main/frontend/src/code-quarkus/quarkus-blurb.scss
src/main/frontend/yarn.lock
src/main/kotlin/io/quarkus/code/model/CodeQuarkusExtension.kt
src/main/kotlin/io/quarkus/code/services/QuarkusExtensionUtils.kt
src/test/kotlin/io/quarkus/code/services/QuarkusExtensionCatalogTest.kt

Fixes #258, Fixes #132
@fbricon @jeffmaury @xorye, you will now have the `guide` link (optional) available in the extension list.

Introduce guide link and enhance extensions actions

---

.gitignore
openshift/template.yaml
pom.xml
src/main/frontend/package.json
src/main/kotlin/io/quarkus/code/services/QuarkusExtensionCatalog.kt
src/main/resources/application.properties
src/test/kotlin/io/quarkus/code/services/QuarkusExtensionCatalogTest.kt
src/test/kotlin/io/quarkus/code/services/QuarkusExtensionUtilsTest.kt
src/test/kotlin/io/quarkus/code/services/QuarkusProjectCreatorTest.kt

- This reverts commit 96a828a6 and add a fix it, it was due to a Config problem in tests without the @QuarkusTest annotation.
- Re-add the order check in project creation tests
- Fix dev mode

Fix problems introduced by Quarkus 1.1.0.Final

---

src/main/frontend/src/code-quarkus/pickers/__tests__/__snapshots__/extensions-picker.spec.tsx.snap
src/main/frontend/src/code-quarkus/quarkus-blurb.tsx

fix: make mobile alert always visible

---

src/main/frontend/src/code-quarkus/code-quarkus.scss
src/main/frontend/src/code-quarkus/config.scss
src/main/frontend/src/code-quarkus/form.scss
src/main/frontend/src/code-quarkus/pickers/__tests__/__snapshots__/extensions-picker.spec.tsx.snap
src/main/frontend/src/code-quarkus/pickers/extensions-picker.scss
src/main/frontend/src/code-quarkus/pickers/extensions-picker.tsx

@edewit could you check I didn't break anything 😅

Improve mobile/tablets layout

---

src/main/kotlin/io/quarkus/code/CodeQuarkusResource.kt
src/main/kotlin/io/quarkus/code/model/QuarkusProject.kt
src/test/kotlin/io/quarkus/code/CodeQuarkusResourceTest.kt

Add test and fix for invalid shortId bug

---

src/main/frontend/package.json
src/main/frontend/src/code-quarkus/code-quarkus.scss
src/main/frontend/src/code-quarkus/code-quarkus.tsx
src/main/frontend/src/code-quarkus/pickers/__tests__/__snapshots__/extensions-picker.spec.tsx.snap
src/main/frontend/src/code-quarkus/pickers/__tests__/__snapshots__/info-picker.spec.tsx.snap
src/main/frontend/yarn.lock

Fix weird animation on NextSteps popup

---

src/main/frontend/src/code-quarkus/code-quarkus.tsx
src/main/frontend/src/code-quarkus/form.tsx
src/main/frontend/src/code-quarkus/pickers/extensions-picker.tsx

Fix "cannot remove extensions by unchecking checkbox"

---

Makefile
README.md
src/main/frontend/src/code-quarkus/next-steps.tsx

update quarkus:dev steps to no longer include the compile directive

---

README.md
src/main/frontend/src/code-quarkus/__tests__/launcher-quarkus.spec.tsx
src/main/frontend/src/code-quarkus/code-quarkus.tsx
src/main/frontend/src/code-quarkus/copy-to-clipboard.tsx
src/main/frontend/src/code-quarkus/next-steps.tsx
src/main/frontend/src/code-quarkus/pickers/__tests__/__snapshots__/info-picker.spec.tsx.snap
src/main/frontend/src/code-quarkus/pickers/__tests__/info-picker.spec.tsx
src/main/frontend/src/code-quarkus/pickers/extensions-picker.tsx
src/main/frontend/src/code-quarkus/pickers/info-picker.tsx
src/main/frontend/src/code-quarkus/quarkus-blurb.tsx
src/main/frontend/src/core/analytics/google-analytics.ts
src/main/frontend/src/core/extended-text-input.tsx
src/main/frontend/src/core/stuff.tsx
src/main/frontend/src/core/toggle-panel/toggle-panel.tsx

Fixes #238 
CC: @emmanuelbernard 
This would totally change the current events on GA, the benefits are:
- easier to understand without doc
- more flexible for future events
Could you please be really critical on this so we try not to change them again..
PS: I would understand if you feel we can't change..
The category gives an overall overview of the popularity of an extension, then you can deep dive to particular actions related to extension 
| Category | Action | Label | Description |
| --- | --- | --- | --- |
| Extension | Used | *Extension ID* | This extension has been used in a project |
| Extension | Copy the command to add it with Maven | *Extension ID* | ... |
| Extension | Copy the command to add it with Gradle | *Extension ID* | ... |
| Extension | Copy GAV | *Extension ID* | …

Change Analytics events proposition

---

src/main/frontend/src/code-quarkus/code-quarkus.scss
src/main/frontend/src/code-quarkus/code-quarkus.tsx
src/main/frontend/src/code-quarkus/config.scss
src/main/frontend/src/code-quarkus/next-steps.tsx
src/main/frontend/src/code-quarkus/pickers/extensions-picker.scss

Suggest application guides for next steps

---

pom.xml
src/main/docker/Dockerfile.native.multistage
src/main/kotlin/io/quarkus/code/services/QuarkusProjectCreator.kt

This will require 1.3.1.Final or master.
(This will need to be merged once I upgrade things to 1.3.1.Final)

Force Java target to 11

---

src/main/frontend/src/code-quarkus/pickers/__tests__/extensions-picker.spec.tsx
src/main/frontend/src/code-quarkus/pickers/extensions-picker-helpers.ts
src/main/frontend/src/code-quarkus/pickers/extensions-picker.tsx
src/main/kotlin/io/quarkus/code/services/QuarkusExtensionUtils.kt

Fixes #305
cc @maxandersen @emmanuelbernard

Introduce ability to filter per tag (preview, ...)

---

Makefile
openshift/template.yaml
src/main/frontend/src/code-quarkus/code-quarkus.tsx
src/main/frontend/src/code-quarkus/config-loader.tsx
src/main/frontend/src/code-quarkus/config.scss
src/main/frontend/src/code-quarkus/header.scss
src/main/frontend/src/code-quarkus/header.tsx
src/main/kotlin/io/quarkus/code/CodeQuarkusResource.kt
src/main/kotlin/io/quarkus/code/config/CodeQuarkusConfig.kt
src/main/kotlin/io/quarkus/code/model/Config.kt
src/test/kotlin/io/quarkus/code/CodeQuarkusResourceTest.kt

Introduce support button feature (disabled by default)

---

src/main/resources/creator/gradlew/gradle/wrapper/gradle-wrapper.properties

Requires https://github.com/quarkusio/quarkus/pull/9434

Bump to Gradle 6.4.1

---

pom.xml
src/main/kotlin/io/quarkus/code/service/GitHubService.kt
src/test/kotlin/io/quarkus/code/model/ProjectDefinitionTest.kt

Should fix https://github.com/quarkusio/code.quarkus.io/issues/382

Fix GitHub client error thrown back as server response

---

src/main/frontend/src/code-quarkus/__tests__/__snapshots__/launcher-quarkus.spec.tsx.snap
src/main/frontend/src/code-quarkus/api/__tests__/quarkus-project-utils.spec.ts
src/main/frontend/src/code-quarkus/api/quarkus-project-utils.ts
src/main/frontend/src/code-quarkus/pickers/extensions-picker.tsx
src/main/frontend/src/code-quarkus/quarkus-project/quarkus-project-edition-form.tsx
src/main/frontend/src/code-quarkus/quarkus-project/quarkus-project-flow.tsx

Issue: #357
What I did was sync the filter value with the query param, so that's easier to share the extension and etc.. And it attend what the issue ask for.

#357 - Syncing filter value with query param.

---

src/main/kotlin/io/quarkus/code/rest/CodeQuarkusResource.kt
src/test/kotlin/io/quarkus/code/rest/CodeQuarkusResourceTest.kt

Add download as POST

---

src/main/kotlin/io/quarkus/code/rest/CodeQuarkusResource.kt
src/main/kotlin/io/quarkus/code/service/QuarkusExtensionCatalogService.kt
src/main/kotlin/io/quarkus/code/service/QuarkusProjectService.kt

Return HTTP 400 instead of 500 when making erroneous extension selection

---

src/main/kotlin/io/quarkus/code/rest/CodeQuarkusResource.kt
src/main/kotlin/io/quarkus/code/service/QuarkusExtensionCatalogService.kt

A simple correction of code smells.

Fixs some code smells

---

src/main/frontend/src/code-quarkus/config.scss
src/main/frontend/src/code-quarkus/extensions-picker/extension-row.scss
src/main/frontend/src/code-quarkus/extensions-picker/extension-tags.tsx
src/main/frontend/src/code-quarkus/extensions-picker/extensions-picker-utils.ts
src/main/kotlin/io/quarkus/code/misc/QuarkusExtensionUtils.kt
src/test/kotlin/io/quarkus/code/misc/QuarkusExtensionUtilsTest.kt

Use code instead of provides-code

---

pom.xml
src/main/frontend/src/code-quarkus/extensions-picker/extension-more-dropdown.tsx

Introduce CLI add extension command

---

.github/workflows/ci-actions.yml
pom.xml
src/main/kotlin/io/quarkus/code/rest/CodeQuarkusHealthCheck.kt
src/main/kotlin/io/quarkus/code/rest/CodeQuarkusResource.kt
src/main/kotlin/io/quarkus/code/service/PlatformService.kt
src/main/resources/application.properties
src/test/kotlin/io/quarkus/code/misc/QuarkusExtensionUtilsTest.kt

NOTE: This only upgrade the version used by code.quarkus.io backend, it won't affect the platform used to generate app
cc @gsmet

Upgrade to io.quarkus:quarkus-bom:2.1.0.Final and improve logging

---

src/main/frontend/src/code-quarkus/api/model.ts
src/main/frontend/src/code-quarkus/extensions-picker/extension-more-dropdown.tsx
src/main/frontend/src/code-quarkus/extensions-picker/extensions-picker.tsx
src/main/kotlin/io/quarkus/code/misc/QuarkusExtensionUtils.kt
src/main/kotlin/io/quarkus/code/model/CodeQuarkusExtension.kt

Introduce bom copy helper in api and UI

---

src/main/frontend/src/code-quarkus/modals/next-steps-modal.tsx
src/main/frontend/src/code-quarkus/quarkus-project/quarkus-project-flow.tsx
src/main/kotlin/io/quarkus/code/misc/QuarkusExtensionUtils.kt
src/test/kotlin/io/quarkus/code/misc/QuarkusExtensionUtilsTest.kt

Fix gradle next step modal and add CLI option

---

src/main/kotlin/io/quarkus/code/model/ProjectDefinition.kt
src/main/kotlin/io/quarkus/code/rest/CodeQuarkusResource.kt
src/main/kotlin/io/quarkus/code/rest/OpenAPIFilter.kt

Fix #512
Signed-off-by: Phillip Kruger <phillip.kruger@gmail.com>

Add Gradle_Kotlin as option for Build in Download API

---

frontend/.env.development
library/.bitmap
library/components/code-quarkus.scss
library/components/code-quarkus.tsx
library/components/extensions-picker/__tests__/__snapshots__/extensions-picker.spec.tsx.snap
library/components/extensions-picker/extension-row.scss
library/components/extensions-picker/extension-row.tsx
library/components/extensions-picker/extension-tags.tsx
library/components/header/code-quarkus-header.scss
library/components/header/stream-picker.scss
library/components/header/stream-picker.tsx
library/components/theme.scss
library/core/components/hover-controlled-dropdown.tsx
library/package-lock.json
library/package.json

Support formatted tag tooltip with an optional link:
Stream picker:

UI Features

---

library/core/components/copy-to-clipboard.scss

Fix vertical alignment in the alert box

---

api/pom.xml
api/src/main/kotlin/io/quarkus/code/model/Stream.kt
api/src/main/kotlin/io/quarkus/code/service/PlatformService.kt
library/.bitmap
library/components/__tests__/launcher-quarkus.spec.tsx
library/components/api/model.ts
library/components/header/stream-picker.scss
library/components/header/stream-picker.tsx
library/components/theme.scss

Support for stream status

---

api/src/main/kotlin/io/quarkus/code/service/PlatformService.kt
library/.bitmap
library/components/header/stream-picker.scss
library/components/theme.scss

Fix stream background

---

.dependabot/config.yml
Makefile
api/src/main/kotlin/io/quarkus/code/service/PlatformService.kt
openshift/code-quarkus-acceptance-test.yaml

- Update dependabot config
- Update Make file to fix lib-link
- Fix NPE when loading platform catalog

Multiple stuff

---

Makefile

Signed-off-by: Phillip Kruger <phillip.kruger@gmail.com>

Fix Makefile spelling mistake

---

api/src/main/kotlin/io/quarkus/code/misc/QuarkusExtensionUtils.kt
frontend/src/theme.scss
library/.bitmap
library/components/api/code-quarkus-api.ts
library/components/api/model.ts
library/components/code-quarkus.scss
library/components/extensions-picker/__tests__/__snapshots__/extensions-picker.spec.tsx.snap
library/components/extensions-picker/extension-search-bar.scss
library/components/extensions-picker/extension-search-bar.tsx
library/components/extensions-picker/extension-tags.tsx
library/components/extensions-picker/extensions-picker.tsx
library/components/extensions-picker/extensions-utils.ts
library/components/extensions-picker/search-results-info.scss
library/components/extensions-picker/search-results-info.tsx

https://quarkusio.zulipchat.com/user_uploads/11321/tTeYEznueEYkVr_6tvDfZ2ZX/Kapture-2021-11-24-at-17.40.50.gif

Introduce the filter helper dropdown

---

library/.bitmap
library/components/extensions-picker/search-results-info.tsx

Fix Small nitpick: No extension**s** found

---

library/components/api/quarkus-project-utils.ts
library/components/code-quarkus.scss
library/components/extensions-picker/extension-more-dropdown.tsx
library/components/extensions-picker/extension-row.scss
library/components/extensions-picker/extension-search-bar.scss
library/components/extensions-picker/extension-search-bar.tsx
library/components/extensions-picker/extensions-origin.tsx
library/components/extensions-picker/extensions-picker.tsx
library/components/extensions-picker/extensions-utils.ts
library/components/extensions-picker/search-results-info.scss
library/components/extensions-picker/search-results-info.tsx

- Fixes #690 
- Fixes #678 
- Display `origin:platform` in the filter bar by default
- Improve filter dropdown
- Use quark icon instead of atom

Mix of UI improvements

---

library/.bitmap
library/components/extensions-picker/extension-row.scss
library/components/extensions-picker/extensions-origin.tsx
library/components/media/platform-icon.svg

Use new Quark Platform Icon

---

api/pom.xml
api/src/test/resources/__snapshots__/QuarkusProjectServiceTest/testCustom/dir-tree.snapshot
api/src/test/resources/__snapshots__/QuarkusProjectServiceTest/testDefault/dir-tree.snapshot
api/src/test/resources/__snapshots__/QuarkusProjectServiceTest/testDefaultZip/dir-tree.snapshot
api/src/test/resources/__snapshots__/QuarkusProjectServiceTest/testGradleKotlin/dir-tree.snapshot
api/src/test/resources/__snapshots__/QuarkusProjectServiceTest/testQuteYaml/dir-tree.snapshot

Bump to Quarkus 2.7.0.Final

---

.github/workflows/code-quarkus-frontend-actions.yml
.github/workflows/code-quarkus-frontend-preview-actions.yml
library/.bitmap
library/components/layout/missing-extension-warning-modal.tsx
library/components/quarkus-project/quarkus-project-flow.tsx

Missing extension warning modal correctly shows the missing extensions ids

---

api/src/main/kotlin/io/quarkus/code/rest/OpenAPIFilter.kt

Signed-off-by: Phillip Kruger <phillip.kruger@gmail.com>

Make sure OpenAPI can still generate on build time

---

Makefile
README.md
api/pom.xml
api/src/main/kotlin/io/quarkus/code/model/Stream.kt
api/src/main/kotlin/io/quarkus/code/service/PlatformInfo.kt
api/src/main/kotlin/io/quarkus/code/service/PlatformService.kt
api/src/main/resources/application.properties
frontend/package.json
library/.bitmap
library/components/api/model.ts
library/components/header/stream-picker.tsx
library/core/components/sentry-boundary.tsx

Display platform version instead of Quarkus core version:
Fixes #754

Display platform version

---

library/components/__tests__/launcher-quarkus.spec.tsx
library/components/api/__tests__/quarkus-project-utils.spec.ts
library/components/api/quarkus-project-utils.ts
library/components/generate-project/generate-button.tsx
library/components/quarkus-project/quarkus-project-edition-form.tsx
library/components/quarkus-project/quarkus-project-flow.tsx

1- Get the project from the local storage in resolveInitialProject():
2- Set the project in local storage when clicking on the button 'Store current app as default'
Override order: Query params > localstorage > default
Fixes #591

Button to store current app as default (in local storage) 

---

frontend/src/theme.scss
library/components/__tests__/launcher-quarkus.spec.tsx
library/components/api/__tests__/quarkus-project-utils.spec.ts
library/components/api/quarkus-project-utils.ts
library/components/code-quarkus.scss
library/components/generate-project/generate-button.tsx
library/components/quarkus-project/quarkus-project-edition-form.tsx

Add button to revert stored default app to original default

---

library/components/api/__tests__/quarkus-project-utils.spec.ts
library/components/api/quarkus-project-utils.ts

fix: Remove platform stream version from user stored customized project

---

api/src/main/kotlin/io/quarkus/code/model/Stream.kt
api/src/main/kotlin/io/quarkus/code/service/PlatformService.kt
library/.bitmap

Use maven qualifier for stream status

---

library/.bitmap
library/components/header/stream-picker.scss
library/components/header/stream-picker.tsx

Show platform stream status on Stream Picker Header

---

acceptance-test/pom.xml
api/pom.xml
api/src/main/kotlin/io/quarkus/code/rest/exceptions/CodestartExceptionMapper.kt
api/src/main/kotlin/io/quarkus/code/rest/exceptions/CodestartStructureExceptionMapper.kt
api/src/main/kotlin/io/quarkus/code/rest/exceptions/IOExceptionMapper.kt
api/src/main/kotlin/io/quarkus/code/rest/exceptions/IllegalArgumentExceptionMapper.kt
api/src/main/kotlin/io/quarkus/code/rest/exceptions/QuarkusCommandExceptionMapper.kt
api/src/main/kotlin/io/quarkus/code/service/QuarkusProjectService.kt

Add exception handlers

---

api/src/main/kotlin/io/quarkus/code/model/Stream.kt
api/src/main/kotlin/io/quarkus/code/service/PlatformService.kt

Fix status in api

---

acceptance-test/pom.xml
api/pom.xml

Fixes https://github.com/quarkusio/quarkus/issues/36707

Quarkus 3.5.0

---

base/src/main/resources/application.properties

This is the upstream issue: https://github.com/quarkusio/quarkus/issues/38155
@iocanel this should be available in ~1h in prod

CORS workaround

---

base/src/main/java/io/quarkus/code/config/CodeQuarkusConfig.java
base/src/main/java/io/quarkus/code/config/UIConfig.java
base/src/main/resources/application.properties
base/src/main/resources/web/community-app/index.jsx
base/src/main/resources/web/index.html
base/src/main/resources/web/lib/components/api/code-quarkus-api.ts
base/src/main/resources/web/lib/components/api/code-quarkus-github-api.ts
community-app/src/test/java/CodeQuarkusCommunityPlaywrightTest.java

#1264  part 2
This is the upstream issue: https://github.com/quarkusio/quarkus/issues/38155

CORS workaround 2

---

base/src/main/resources/web/lib/components/extensions-picker/extensions-utils.ts
base/src/test/java/io/quarkus/code/CodeQuarkusPlaywrightTest.java

Here is a PR for the code.quarkus.io part of https://github.com/quarkusio/quarkus/issues/39204 .
As mentioned on Zulip, I wasn't able to build this project locally. CI in my fork looks happy but no idea if it actually works...

Also search on extension's artifactId

---

.gitignore
base/src/main/resources/web/lib/components/api/quarkus-project-utils.ts
base/src/main/resources/web/lib/components/code-quarkus.scss
base/src/main/resources/web/lib/components/modals/next-steps-modal.tsx
base/src/main/resources/web/lib/components/quarkus-project/quarkus-project-flow.tsx

Fixes https://github.com/quarkusio/code.quarkus.io/issues/1176

Add GH button on next-step modal

---

acceptance-test/pom.xml
base/src/main/resources/application.properties
community-app/pom.xml
pom.xml

See quarkusio/quarkus#39295 for details on the change.
/cc @ia3andy

Update to renamed configuration keys

---

base/src/main/resources/web/lib/components/header/stream-picker.scss
base/src/main/resources/web/lib/components/header/stream-picker.tsx

Show LTS flag on streams

---

base/src/main/java/io/quarkus/code/misc/QuarkusExtensionUtils.java
base/src/main/java/io/quarkus/code/model/CodeQuarkusExtension.java
base/src/main/java/io/quarkus/code/service/PlatformService.java
base/src/main/resources/web/lib/components/api/code-quarkus-api.ts
base/src/main/resources/web/lib/components/api/model.ts
base/src/main/resources/web/lib/components/extensions-picker/extension-row.scss
base/src/main/resources/web/lib/components/extensions-picker/extension-row.tsx
base/src/main/resources/web/lib/components/extensions-picker/extensions-picker.tsx
base/src/main/resources/web/lib/components/extensions-picker/presets-panel.tsx
base/src/main/resources/web/lib/components/extensions-picker/selected-extensions.tsx
base/src/main/resources/web/lib/components/generate-project/extensions-cart.tsx
base/src/main/resources/web/lib/components/quarkus-project/quarkus-project-edition-form.tsx

Introduce transitive extensions in api and UI

---

.github/workflows/quarkus-ecosystem.actions.yml

Fix Ecosystem CI
